import 'package:flutter/material.dart';

// const backgroundColor = Color.fromRGBO(19, 28, 33, 1);
// const tabColor = Color.fromRGBO(0, 167, 131, 1);
const primaryColor = Colors.blue;
const backgroundColor = Colors.black;
const textColor = Color.fromRGBO(241, 241, 242, 1);
const textFieldBackgroundColor = Color.fromRGBO(35, 35, 35, 1);
const bottomBackgroundColor = Color.fromRGBO(20, 20, 20, 1);
const appBarColor = Colors.black;
const webAppBarColor = Color.fromRGBO(42, 47, 50, 1);
const messageColor = Color.fromRGBO(5, 96, 98, 1);
const senderMessageColor = Color.fromRGBO(37, 45, 49, 1);
const tabColor = Colors.black;
const searchBarColor = Color.fromRGBO(50, 55, 57, 1);
const dividerColor = Color.fromRGBO(37, 45, 50, 1);
const chatBarMessage = Color.fromRGBO(30, 36, 40, 1);
const mobileChatBoxColor = Color.fromRGBO(31, 44, 52, 1);
const greyColor = Colors.grey;
const blackColor = Colors.black;
const replyMyBorderColor = Color.fromRGBO(0, 167, 131, 1);
const replyOtherBorderColor = Color.fromRGBO(0, 131, 167, 1);
